language: julia
os:
  - linux
julia:
  - 1.2
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
  - julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/JuliaPackaging/BinaryBuilder.jl", rev="master"))'
  - julia -e 'import Pkg; Pkg.add("BinaryProvider")'
script:
  - julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: V/2xo1zzj3M/We7tGjHKMB0BU0eiN8MfhICwSQOWJCGjZ2Nz74PAf8/LKm6ZVs1A79pLig57ewreOHJvuUbkGmU8+Ig09dItfcK83cx5MqjMyFYC692yucOyXWwLOQVTV4DrsiulXmB+NQS0PIH0ALypPMzah+ToysaZ53ycyuLnOuEfuk9joHA8Ual9tfD3gYfZ4CKTITAYRQs2+8Wv9PGCHkxhgN5L7NJBX4O0PpJMKhsevro1tOq+nNxpbNVSlLCo27iCEwZL5qjQBaESrNCMwyxw1YoPXYs4FD2kYxUZnGqhs8W+snjXMB/j23qKely1WQorWAqLKpBxbRqBx0/EnfUNbit78sNUnLRYXTDkMQ72Tte5lMLGxS+vAYgEaDq/pZCHnN/PRAXQYmp0r08hLqkS0garSNKPEGBvlIpOGIlJxe9JM8Ba6J68lEBQXDp69IO9J6oJG3TCAvUwoRMbuq8CRkYCgfYXx/nLKw52dfDQW5I/r6X7itLz9x76uAyKmDeQxd6rQHYmL5fp6crMAK4u1687RIlapZDlIewE9oxkX2bfgop2Dub/aT+z5HvXLYiC4eReJjKzJyuPhprC9wOurwkUwtnvbh2mc4fq1OBUXj9AWEz1AzMm4K92JDDeDa2rIjy5raO9oVwrtOTTbaM4WE+WfYUX5UMrNiM=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: daviehh/ArpackBuilder
    tags: true
